### ISSUE TITLE
BARQUE ERROR: flash is not installed

### ISSUE THREAD

**Issue by emagallong** [enormandeau/barque#4]
Hi there:
I was trying to run the test samples but I have the following error: " BARQUE ERROR: flash is not installed". However, flash is installed already along with the rest of the dependencies. 
What can I do to fix this error?
Thanks in advance

**Comment by enormandeau** [comment]
Hi,

If you can launch `vsearch` in the same environment that you launch `Barque`, then deleting lines 71 to 83 of `01_scripts/00_validate_project.sh` is going to bypass checking for `vsearch` and its version.

However, if the validation script does not see `vsearch`, perhaps it is not available in your environment and this fix won't work.

Tell me if this works!

**Comment by emagallong** [comment]
Thanks for your response... I'm getting the same error :(

**Comment by enormandeau** [comment]
I suspect you test vsearch and use barque in different environments, like using SLURM on a server. If this is the case, perhaps you need to do something like `module load vsearch` in your SLURM script.

If this does not describe your problem, please give me more information about the computer where you are trying to run barque.
