### ISSUE TITLE
Parallel (2016122) is too old; need version 20180101+ to run Barque

### ISSUE THREAD

**Issue by mkmor** [enormandeau/barque#5]
We have installed the latest versions of Barque (v1.7.8) and parallel (20230722), yet Barque is unable to recognize the new parallel version. 

```
$ ./barque 02_info.barque_config.sh
...
- bold Database found
- 84 Samples found in 04_data
- vsearch is recent enough
- python3 is recent enough
- R is recent enough

/!\ WARNING /!\

parallel (20161222) is too old
You need version 20180101+ to run Barque

>>> STOPPING BARQUE <<<
```
I'm not sure whether this is an issue with Barque itself. Do you have any advice on how to remedy this? Thanks!

**Comment by enormandeau** [comment]
I suggest you install a more recent version of parallel. 2016 is a bit old. Parallel is very easy to compile and install.

You can find it here: https://www.gnu.org/software/parallel/

Take care,

Eric
