### ISSUE TITLE
pipeline for single end

### ISSUE THREAD

**Issue by sebapoljak** [enormandeau/barque#6]
Dear Eric Normandeau,

We would like to run the pipeline only with the R1 sequences (single end read), Is it possible? How? Thank you

**Comment by enormandeau** [comment]
Hi. Do the forward sequences contain both of the primer sequences? If yes, we could cheat the pipeline to use those. If not, I guess we could add them and then cheat barque the same way.

Could you please send me a small dataset (maybe only 1000 reads for 4 samples) so I can test things and potentially write a script to prepare the data? I would also need the sequence of the primers.

**Comment by sebapoljak** [comment]
Thank you for your response.
The forward sequence contain only the forward primer sequences (MFish Forward).
Here I send you 4 samples. Thank you in advanced!
[mifish-c3_S40_L001_R1_001.fastq.gz](https://github.com/enormandeau/barque/files/12818007/mifish-c3_S40_L001_R1_001.fastq.gz)
[mifish-rem1_S36_L001_R1_001.fastq.gz](https://github.com/enormandeau/barque/files/12818009/mifish-rem1_S36_L001_R1_001.fastq.gz)
[mifish-rem2_S37_L001_R1_001.fastq.gz](https://github.com/enormandeau/barque/files/12818010/mifish-rem2_S37_L001_R1_001.fastq.gz)
[mifish-2ma_S34_L001_R1_001.fastq.gz](https://github.com/enormandeau/barque/files/12818011/mifish-2ma_S34_L001_R1_001.fastq.gz)

**Comment by allentian1** [comment]
Is there a way to do this?

**Comment by enormandeau** [comment]
I have not yet implemented this and it cannot be a priority unfortunately. I don't know if I'll ever have time to do this. However, if you found a way to create false reverse reads that contained the reverse primer it would work.
